/**
 * Report Generation Service
 * Creates comprehensive project reports from commit history and stories
 */

import { Project, Commit, Story, RepoInsights } from '../models';

export interface ReportOptions {
  includeCommitList: boolean;
  includeStories: boolean;
  includeInsights: boolean;
  includeFileChanges: boolean;
  dateRange?: { start: Date; end: Date };
  format: 'markdown' | 'html' | 'json';
}

export interface ReportData {
  project: Project;
  commits: Commit[];
  stories: Story[];
  insights: RepoInsights | null;
  generatedAt: Date;
  options: ReportOptions;
}

const defaultOptions: ReportOptions = {
  includeCommitList: true,
  includeStories: true,
  includeInsights: true,
  includeFileChanges: true,
  format: 'markdown',
};

/**
 * Generate a comprehensive project report
 */
export function generateReport(data: ReportData): string {
  const { format } = data.options;
  
  switch (format) {
    case 'html':
      return generateHtmlReport(data);
    case 'json':
      return generateJsonReport(data);
    case 'markdown':
    default:
      return generateMarkdownReport(data);
  }
}

/**
 * Generate Markdown format report
 */
function generateMarkdownReport(data: ReportData): string {
  const { project, commits, stories, insights, generatedAt, options } = data;
  
  let report = `# Project Report: ${project.name}

> Generated on ${generatedAt.toLocaleString()}

## Overview

- **Repository:** ${project.path}
- **Total Commits Analyzed:** ${commits.length}
- **Stories Generated:** ${stories.length}

---

`;

  // Executive Summary
  if (options.includeInsights && insights) {
    report += `## Executive Summary

This report covers ${commits.length} commits from the project "${project.name}". 
${getInsightsSummary(commits, stories)}

### Key Metrics

| Metric | Value |
|--------|-------|
| Total Commits | ${commits.length} |
| Contributors | ${getUniqueAuthors(commits).length} |
| Stories | ${stories.length} |
| Files Changed | ${getUniqueFiles(commits).size} |

---

`;
  }

  // Stories Section
  if (options.includeStories && stories.length > 0) {
    report += `## Commit Stories

${stories.map((story, index) => `
### ${index + 1}. ${story.title}

**Type:** ${story.type.toUpperCase()} | **Date:** ${new Date(story.timestamp).toLocaleDateString()} | **Commits:** ${story.commits.length}

${story.summary}

<details>
<summary>View ${story.commits.length} commits</summary>

${story.commits.map(c => `- \`${c.hash.substring(0, 7)}\` ${c.message}`).join('\n')}

</details>

**Files affected:** ${story.files.length}
`).join('\n')}

---

`;
  }

  // Commits by Type
  report += `## Commits by Type

${getCommitsByTypeTable(commits)}

---

`;

  // Contributors
  report += `## Contributors

${getContributorsTable(commits)}

---

`;

  // Timeline
  report += `## Activity Timeline

${getTimelineSection(commits)}

---

`;

  // Commit List
  if (options.includeCommitList) {
    report += `## Full Commit List

| Hash | Author | Date | Message |
|------|--------|------|---------|
${commits.slice(0, 100).map(c => 
  `| \`${c.hash.substring(0, 7)}\` | ${c.author} | ${new Date(c.date).toLocaleDateString()} | ${escapeMarkdown(c.message.substring(0, 60))}${c.message.length > 60 ? '...' : ''} |`
).join('\n')}

${commits.length > 100 ? `\n*Showing 100 of ${commits.length} commits*\n` : ''}

---

`;
  }

  // Footer
  report += `
---

*Report generated by Commit Story Desktop*
`;

  return report;
}

/**
 * Generate HTML format report
 */
function generateHtmlReport(data: ReportData): string {
  const { project, commits, stories, insights, generatedAt, options } = data;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project Report: ${escapeHtml(project.name)}</title>
  <style>
    :root {
      --bg: #0d1117;
      --card-bg: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --text-muted: #8b949e;
      --primary: #58a6ff;
      --green: #3fb950;
      --red: #f85149;
      --yellow: #d29922;
      --purple: #a371f7;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem;
      max-width: 1200px;
      margin: 0 auto;
    }
    h1, h2, h3 { margin: 1.5rem 0 1rem; color: var(--text); }
    h1 { font-size: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
    h2 { font-size: 1.5rem; color: var(--primary); }
    h3 { font-size: 1.2rem; }
    p { margin: 0.5rem 0; color: var(--text-muted); }
    .meta { color: var(--text-muted); font-size: 0.9rem; margin-bottom: 2rem; }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1.5rem;
      margin: 1rem 0;
    }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; }
    .stat { text-align: center; padding: 1rem; }
    .stat-value { font-size: 2rem; font-weight: bold; color: var(--primary); }
    .stat-label { font-size: 0.9rem; color: var(--text-muted); }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
    th { color: var(--text-muted); font-weight: 600; }
    code { 
      background: var(--bg); 
      padding: 0.2rem 0.4rem; 
      border-radius: 4px; 
      font-family: 'SFMono-Regular', Consolas, monospace;
      font-size: 0.9em;
    }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
    }
    .badge-feature { background: rgba(88, 166, 255, 0.2); color: var(--primary); }
    .badge-fix { background: rgba(248, 81, 73, 0.2); color: var(--red); }
    .badge-docs { background: rgba(63, 185, 80, 0.2); color: var(--green); }
    .badge-refactor { background: rgba(163, 113, 247, 0.2); color: var(--purple); }
    .badge-chore { background: rgba(139, 148, 158, 0.2); color: var(--text-muted); }
    .story-card { margin: 1rem 0; }
    .story-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.5rem; }
    .story-title { font-size: 1.1rem; font-weight: 600; }
    .story-meta { font-size: 0.85rem; color: var(--text-muted); }
    .story-summary { color: var(--text-muted); margin: 0.5rem 0; }
    .commit-list { font-size: 0.9rem; margin-top: 1rem; }
    .commit-item { padding: 0.5rem 0; border-bottom: 1px solid var(--border); }
    .commit-hash { color: var(--primary); font-family: monospace; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--text-muted); font-size: 0.85rem; text-align: center; }
  </style>
</head>
<body>
  <h1>📊 Project Report: ${escapeHtml(project.name)}</h1>
  <p class="meta">Generated on ${generatedAt.toLocaleString()} • ${commits.length} commits analyzed</p>

  <div class="card">
    <h2>📈 Overview</h2>
    <div class="grid">
      <div class="stat">
        <div class="stat-value">${commits.length}</div>
        <div class="stat-label">Total Commits</div>
      </div>
      <div class="stat">
        <div class="stat-value">${getUniqueAuthors(commits).length}</div>
        <div class="stat-label">Contributors</div>
      </div>
      <div class="stat">
        <div class="stat-value">${stories.length}</div>
        <div class="stat-label">Stories</div>
      </div>
      <div class="stat">
        <div class="stat-value">${getUniqueFiles(commits).size}</div>
        <div class="stat-label">Files Changed</div>
      </div>
    </div>
  </div>

  ${options.includeStories && stories.length > 0 ? `
  <h2>📖 Commit Stories</h2>
  ${stories.map(story => `
  <div class="card story-card">
    <div class="story-header">
      <div>
        <div class="story-title">${escapeHtml(story.title)}</div>
        <div class="story-meta">${new Date(story.timestamp).toLocaleDateString()} • ${story.commits.length} commits • ${story.files.length} files</div>
      </div>
      <span class="badge badge-${story.type}">${story.type}</span>
    </div>
    <p class="story-summary">${escapeHtml(story.summary)}</p>
  </div>
  `).join('')}
  ` : ''}

  <h2>👥 Contributors</h2>
  <div class="card">
    <table>
      <thead>
        <tr><th>Author</th><th>Commits</th><th>Percentage</th></tr>
      </thead>
      <tbody>
        ${getContributorRows(commits)}
      </tbody>
    </table>
  </div>

  <h2>📝 Commits by Type</h2>
  <div class="card">
    <table>
      <thead>
        <tr><th>Type</th><th>Count</th><th>Percentage</th></tr>
      </thead>
      <tbody>
        ${getTypeRows(commits)}
      </tbody>
    </table>
  </div>

  ${options.includeCommitList ? `
  <h2>📋 Recent Commits</h2>
  <div class="card">
    <div class="commit-list">
      ${commits.slice(0, 50).map(c => `
      <div class="commit-item">
        <span class="commit-hash">${c.hash.substring(0, 7)}</span>
        <span>${escapeHtml(c.message.substring(0, 80))}${c.message.length > 80 ? '...' : ''}</span>
        <span class="story-meta"> — ${c.author}, ${new Date(c.date).toLocaleDateString()}</span>
      </div>
      `).join('')}
      ${commits.length > 50 ? `<p class="story-meta">Showing 50 of ${commits.length} commits</p>` : ''}
    </div>
  </div>
  ` : ''}

  <footer>
    Report generated by Commit Story Desktop
  </footer>
</body>
</html>`;
}

/**
 * Generate JSON format report
 */
function generateJsonReport(data: ReportData): string {
  const { project, commits, stories, insights, generatedAt } = data;
  
  const authors = getUniqueAuthors(commits);
  const commitsByType = getCommitsByType(commits);
  
  const report = {
    meta: {
      generatedAt: generatedAt.toISOString(),
      generator: 'Commit Story Desktop',
      version: '1.0.0',
    },
    project: {
      name: project.name,
      path: project.path,
    },
    summary: {
      totalCommits: commits.length,
      totalContributors: authors.length,
      totalStories: stories.length,
      totalFilesChanged: getUniqueFiles(commits).size,
      dateRange: {
        earliest: commits.length > 0 ? commits[commits.length - 1].date : null,
        latest: commits.length > 0 ? commits[0].date : null,
      },
    },
    commitsByType: Object.fromEntries(commitsByType),
    contributors: authors.map(author => ({
      name: author,
      commits: commits.filter(c => c.author === author).length,
    })),
    stories: stories.map(s => ({
      id: s.id,
      title: s.title,
      type: s.type,
      summary: s.summary,
      timestamp: s.timestamp,
      commitCount: s.commits.length,
      fileCount: s.files.length,
      commits: s.commits.map(c => c.hash),
      files: s.files,
    })),
    commits: commits.map(c => ({
      hash: c.hash,
      author: c.author,
      date: c.date,
      message: c.message,
    })),
  };
  
  return JSON.stringify(report, null, 2);
}

// Helper functions

function getUniqueAuthors(commits: Commit[]): string[] {
  return [...new Set(commits.map(c => c.author))];
}

function getUniqueFiles(commits: Commit[]): Set<string> {
  const files = new Set<string>();
  commits.forEach(c => {
    c.files?.forEach(f => files.add(f.path));
  });
  return files;
}

function getCommitsByType(commits: Commit[]): Map<string, number> {
  const types = new Map<string, number>();
  
  commits.forEach(commit => {
    const type = extractCommitType(commit.message);
    types.set(type, (types.get(type) || 0) + 1);
  });
  
  return types;
}

function extractCommitType(message: string): string {
  const match = message.match(/^(feat|fix|docs|refactor|style|test|chore|build|ci|perf)(\(.+\))?:/i);
  return match ? match[1].toLowerCase() : 'other';
}

function getInsightsSummary(commits: Commit[], stories: Story[]): string {
  const authors = getUniqueAuthors(commits);
  const types = getCommitsByType(commits);
  
  const featureCount = types.get('feat') || 0;
  const fixCount = types.get('fix') || 0;
  
  let summary = '';
  
  if (featureCount > 0) {
    summary += `${featureCount} new feature${featureCount > 1 ? 's were' : ' was'} added. `;
  }
  if (fixCount > 0) {
    summary += `${fixCount} bug fix${fixCount > 1 ? 'es were' : ' was'} implemented. `;
  }
  if (authors.length > 1) {
    summary += `${authors.length} contributors collaborated on this project.`;
  }
  
  return summary || 'Various improvements and changes were made.';
}

function getCommitsByTypeTable(commits: Commit[]): string {
  const types = getCommitsByType(commits);
  const sorted = [...types.entries()].sort((a, b) => b[1] - a[1]);
  
  let table = '| Type | Count | Percentage |\n|------|-------|------------|\n';
  
  sorted.forEach(([type, count]) => {
    const pct = ((count / commits.length) * 100).toFixed(1);
    table += `| ${type.charAt(0).toUpperCase() + type.slice(1)} | ${count} | ${pct}% |\n`;
  });
  
  return table;
}

function getContributorsTable(commits: Commit[]): string {
  const authors = getUniqueAuthors(commits);
  const authorCounts = authors.map(author => ({
    author,
    count: commits.filter(c => c.author === author).length,
  })).sort((a, b) => b.count - a.count);
  
  let table = '| Contributor | Commits | Percentage |\n|-------------|---------|------------|\n';
  
  authorCounts.forEach(({ author, count }) => {
    const pct = ((count / commits.length) * 100).toFixed(1);
    table += `| ${author} | ${count} | ${pct}% |\n`;
  });
  
  return table;
}

function getContributorRows(commits: Commit[]): string {
  const authors = getUniqueAuthors(commits);
  const authorCounts = authors.map(author => ({
    author,
    count: commits.filter(c => c.author === author).length,
  })).sort((a, b) => b.count - a.count);
  
  return authorCounts.map(({ author, count }) => {
    const pct = ((count / commits.length) * 100).toFixed(1);
    return `<tr><td>${escapeHtml(author)}</td><td>${count}</td><td>${pct}%</td></tr>`;
  }).join('');
}

function getTypeRows(commits: Commit[]): string {
  const types = getCommitsByType(commits);
  const sorted = [...types.entries()].sort((a, b) => b[1] - a[1]);
  
  return sorted.map(([type, count]) => {
    const pct = ((count / commits.length) * 100).toFixed(1);
    return `<tr><td>${type.charAt(0).toUpperCase() + type.slice(1)}</td><td>${count}</td><td>${pct}%</td></tr>`;
  }).join('');
}

function getTimelineSection(commits: Commit[]): string {
  const byMonth = new Map<string, number>();
  
  commits.forEach(commit => {
    const date = new Date(commit.date);
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
    byMonth.set(key, (byMonth.get(key) || 0) + 1);
  });
  
  const sorted = [...byMonth.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  
  let timeline = '| Month | Commits |\n|-------|--------|\n';
  sorted.forEach(([month, count]) => {
    const [year, m] = month.split('-');
    const monthName = new Date(parseInt(year), parseInt(m) - 1).toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
    timeline += `| ${monthName} | ${count} |\n`;
  });
  
  return timeline;
}

function escapeMarkdown(text: string): string {
  return text.replace(/[|\\`*_{}[\]()#+\-.!]/g, '\\$&');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export { defaultOptions };
